workflows:
  android-development:
    name: Android Development Build
    max_build_duration: 120
    environment:
      node: latest
      java: 17
      xcode: latest
      cocoapods: default
      EXPO_TOKEN: XFqyR8tcNlFCWvYfxS328f0BDTI_OXNbdJWnKwfp
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
    scripts:
      - name: Install dependencies
        script: |
          npm install -g @expo/cli eas-cli
          npm install
      - name: Set up environment variables
        script: |
          # Set defaults if variables are not provided
          echo "REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL:-your_supabase_url_here}" >> .env
          echo "REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY:-your_supabase_key_here}" >> .env
          echo "GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-your_maps_key_here}" >> .env
      - name: Build Android development APK
        script: |
          npx expo install --fix
          echo "Logging into EAS..."
          npx eas login --access-token "$EXPO_TOKEN"
          npx eas build --platform android --profile development --non-interactive
    artifacts:
      - build/**
      - "*.apk"
      - "*.aab"

  ios-development:
    name: iOS Development Build
    max_build_duration: 120
    environment:
      node: latest
      java: 17
      xcode: latest
      cocoapods: default
      EXPO_TOKEN: XFqyR8tcNlFCWvYfxS328f0BDTI_OXNbdJWnKwfp
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install -g @expo/cli eas-cli
          npm install
      - name: Set up environment variables
        script: |
          # Set defaults if variables are not provided
          echo "REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL:-your_supabase_url_here}" >> .env
          echo "REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY:-your_supabase_key_here}" >> .env
          echo "GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-your_maps_key_here}" >> .env
      - name: Build iOS development app
        script: |
          npx expo install --fix
          echo "Logging into EAS..."
          npx eas login --access-token "$EXPO_TOKEN"
          npx eas build --platform ios --profile development --non-interactive
    artifacts:
      - build/**
      - "*.ipa"
    # publishing:
    #   app_store_connect:
    #     api_key: $APP_STORE_CONNECT_PRIVATE_KEY
    #     key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
    #     issuer_id: $APP_STORE_CONNECT_ISSUER_ID
    #     submit_to_testflight: false

  android-production:
    name: Android Production Build
    max_build_duration: 120
    environment:
      node: latest
      java: 17
      xcode: latest
      cocoapods: default
      EXPO_TOKEN: XFqyR8tcNlFCWvYfxS328f0BDTI_OXNbdJWnKwfp
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
      tag_patterns:
        - pattern: "v*"
          include: true
    scripts:
      - name: Install dependencies
        script: |
          npm install -g @expo/cli eas-cli
          npm install
      - name: Set up environment variables
        script: |
          # Set defaults if variables are not provided
          echo "REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL:-your_supabase_url_here}" >> .env
          echo "REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY:-your_supabase_key_here}" >> .env
          echo "GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-your_maps_key_here}" >> .env
      - name: Build Android production AAB
        script: |
          npx expo install --fix
          echo "Logging into EAS..."
          npx eas login --access-token "$EXPO_TOKEN"
          npx eas build --platform android --profile production --non-interactive
    artifacts:
      - build/**
      - "*.apk"
      - "*.aab"
