workflows:
  android-dev:
    name: Android Development Build
    max_build_duration: 120
    environment:
      node: latest
      java: 17
      EXPO_TOKEN: XFqyR8tcNlFCWvYfxS328f0BDTI_OXNbdJWnKwfp
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Setup environment
        script: |
          # Set defaults if variables are not provided
          echo "REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL:-your_supabase_url_here}" >> .env
          echo "REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY:-your_supabase_key_here}" >> .env
          echo "GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-your_maps_key_here}" >> .env
      - name: Build Android APK
        script: npx expo build:android --type apk --no-publish
    artifacts:
      - "*.apk"

  android-production:
    name: Android Production Build
    max_build_duration: 120
    environment:
      node: latest
      java: 17
      EXPO_TOKEN: XFqyR8tcNlFCWvYfxS328f0BDTI_OXNbdJWnKwfp
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Setup environment
        script: |
          # Set defaults if variables are not provided
          echo "REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL:-your_supabase_url_here}" >> .env
          echo "REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY:-your_supabase_key_here}" >> .env
          echo "GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY:-your_maps_key_here}" >> .env
      - name: Build Android AAB
        script: npx expo build:android --type app-bundle --no-publish
    artifacts:
      - "*.aab"
